#!/usr/bin/env Rscript
# Declarative manifest of every file the staging bucket must carry.
#
# Reimplemented from MotrpacHumanPreSuspensionAnalysis/data-raw/google_cloud_bucket_checks/
# required_structure.R — not vendored. It produces the same table shape from the same
# source object, but the dplyr case_when pipeline is base R here and the row builders are
# reorganized, so there is no line-by-line correspondence to mark changes against. What
# changed in SUBSTANCE is listed under "Adapted from upstream" below.
# (lib/expected_columns.R is the vendored file in this stage: it keeps upstream's `=`
# style and its diff is small enough to read directly.)
#
# Columns:
#   ome            — ome string as used in BIC file naming
#   tissue         — high-level tissue category (adipose, blood, muscle)
#   tissue_code    — BIC tissue code used in file names (e.g. t06-muscle)
#   data_category  — one of: qc-norm, metadata, da, imputed
#   data_details   — subcategory string in the file name
#   required       — TRUE = validation fails if absent; FALSE = reported, never fatal
#   gcs_subdir     — top-level bucket subdirectory
#   affected_pkg   — "data", "analysis", or "both"

# ---- Adapted from upstream ---------------------------------------------------------
#
# 1. OME_TISSUE_CODE is read from the preflight data object, not from the installed
#    MotrpacHumanPreSuspensionAnalysis package. Stage 2 validates a bucket built by Stage
#    1 and must not depend on the package that bucket will go on to update — the same
#    dependency step 12 dropped when it stopped falling back to
#    load_differential_analysis().
#
# 2. clinical_chemistry/ is gone. Upstream appends clinical-chemistry rows by hand
#    against a clinical_chemistry/ subdir, and 05_validate_structure.R hardcodes
#    `if (ome == "clinical-chemistry") tissue_code = "t02-plasma"` to make them resolve.
#    The two clinical assays are now ordinary omes in OME_TISSUE_CODE — prot-clinical
#    under proteomics/, metab-t-clinical under metabolomics-targeted/ — so they are
#    generated by the same loop as everything else and the special case is unnecessary.
#
#    It is off the manifest because it is the deprecated predecessor of those two assays
#    and nothing regenerates it: all 9 of its analytes are covered by the pair
#    (CK/Glucagon/Insulin -> prot-clinical, Glucose/Lactate/Glycerol/NEFA/KET/Cortisol ->
#    metab-t-clinical) over the same 1032 samples. It was deleted from the staging bucket
#    on 2026-08-12 once those eight v2.0 files were verified in place.
#
#    Production c1.3 still carries it, so `SEED_STAGING=1` mirroring production into a new
#    staging bucket re-inherits the subdir. Step 03 reports it as ORPHANED when that
#    happens; retiring it is a deletion, which no upload run performs on its own.
#
# 3. metab and clinical DA rows now exist. Upstream's da_details case_when lists only
#    the five non-metab omes, so every metab pair fell through to NA and .da_rows() was
#    never called for it — 34 of the 48 DA files in the bucket had no manifest entry and
#    were never validated. All non-methylcap DA is dream-acute.
#
# 4. lab-* omes are excluded alongside metab-meta-reg. They are the clinical inputs
#    (lab-ck, lab-conv, lab-crt, lab-glc, lab-ins) that step 06 folds into prot-clinical
#    and metab-t-clinical; they ship no files of their own.
#
# 5. imputed rows added for prot-pr / prot-ph. The four *_imputed_log2-mn_* matrices sit
#    in proteomics/qc-norm/ and are in the bucket but absent from the upstream manifest.
#    Optional: they are a proteomics-only artifact.
#
# 6. resources/ rows added. The feature-to-gene mapping and the metabolite-CV table are
#    Stage 1 outputs that upstream's ome x tissue manifest has no shape for.

OME_TISSUE_CODE <- readRDS(file.path(.BH_ROOT, "scripts", "00_preflight", "data", "OME_TISSUE_CODE.rds"))

# Omes with no staging files of their own.
EXCLUDED_OMES <- c("metab-meta-reg", "lab-ck", "lab-conv", "lab-crt", "lab-glc", "lab-ins")

# The two clinical assays are absolute-quantification panels; every other ome carries the
# transform its qc-norm matrix was written on.
.qc_details <- function(ome) {
  if (ome %in% c("prot-clinical", "metab-t-clinical")) return("absolute")
  if (ome %in% c("transcript-rna-seq", "epigen-atac-seq")) return("log-cpm")
  if (ome == "epigen-methylcap-seq") return("beta-values")
  if (ome %in% c("prot-pr", "prot-ph")) return("log2-mn")
  if (ome == "prot-ol") return("log2")
  if (grepl("^metab", ome)) return("log2")
  NA_character_
}

.gcs_subdir <- function(ome) {
  if (ome == "transcript-rna-seq") return("transcriptomics")
  if (grepl("^prot", ome))         return("proteomics")
  if (grepl("^epigen", ome))       return("epigenomics")
  if (grepl("^metab-u", ome))      return("metabolomics-untargeted")
  if (grepl("^metab-t", ome))      return("metabolomics-targeted")
  NA_character_
}

# MethylCap DA is external MALAX GLMM output copied verbatim; everything else is dream.
.da_details <- function(ome) {
  if (ome == "epigen-methylcap-seq") "malax-glmm-acute" else "dream-acute"
}

.row <- function(ome, tissue, tissue_code, data_category, data_details,
                 required = TRUE, gcs_subdir, affected_pkg) {
  data.frame(
    ome = ome, tissue = tissue, tissue_code = tissue_code,
    data_category = data_category, data_details = data_details,
    required = required, gcs_subdir = gcs_subdir, affected_pkg = affected_pkg,
    stringsAsFactors = FALSE
  )
}

.pair_rows <- function(ome, tissue, tissue_code) {
  subdir <- .gcs_subdir(ome)
  rows <- rbind(
    .row(ome, tissue, tissue_code, "qc-norm",  .qc_details(ome), gcs_subdir = subdir, affected_pkg = "data"),
    .row(ome, tissue, tissue_code, "metadata", "features",       gcs_subdir = subdir, affected_pkg = "data"),
    .row(ome, tissue, tissue_code, "metadata", "samples",        gcs_subdir = subdir, affected_pkg = "data"),
    .row(ome, tissue, tissue_code, "metadata", "removed-samples", required = FALSE,
         gcs_subdir = subdir, affected_pkg = "analysis"),
    .row(ome, tissue, tissue_code, "da", .da_details(ome), gcs_subdir = subdir, affected_pkg = "analysis")
  )
  # Adaptation 5: the imputed matrix is written only for the two label-free proteomics
  # assays, and it lands in qc-norm/ beside the matrix it was imputed from.
  # Required, not optional: the row is only generated for the two omes that produce one,
  # so every row generated here corresponds to a file that must exist. Leaving it optional
  # would let a regression that drops an imputed matrix pass validation.
  if (ome %in% c("prot-pr", "prot-ph")) {
    rows <- rbind(rows, .row(ome, tissue, tissue_code, "imputed", "log2-mn",
                             gcs_subdir = subdir, affected_pkg = "data"))
  }
  rows
}

.pairs <- OME_TISSUE_CODE[!OME_TISSUE_CODE$ome %in% EXCLUDED_OMES, , drop = FALSE]

required_structure <- do.call(rbind, lapply(seq_len(nrow(.pairs)), function(i) {
  r <- .pairs[i, ]
  .pair_rows(r$ome, r$tissue, r$tissue_code)
}))

# ---- resources/ --------------------------------------------------------------------
# Not ome x tissue shaped, so these are named by their file stem rather than assembled
# from BIC fields. Kept in a separate table the validator checks by path.
#
# `versioned` says how the stem meets its file name: TRUE means a _v<major>.<minor>
# suffix, FALSE means the stem IS the name and only the extension follows. Every row is
# TRUE: as of v2.0 the collection carries a version token on every file, which
# config/file_versions.json states and enforces by holding an entry for all of them,
# the two offline caches step 06 publishes included. The TxDb and the RefMet snapshot
# are pinned to an external release rather than to this collection, so their version
# token tracks the release that last changed the cache, not the upstream they came from.
#
# The caches are optional because the released buckets do not carry them yet: publishing
# them under resources/ is what makes the bucket their distribution point, and until a
# cycle has actually uploaded them their absence is the expected state, not a failure.
REQUIRED_RESOURCES <- data.frame(
  rel_stem     = c("resources/motrpac-mappings-human-feature-to-gene",
                   "resources/motrpac_human-precovid_metabolite-cv",
                   "resources/txdb_hsapiens_ensembl_v105",
                   "resources/motrpac_human-precovid_refmet-map",
                   "resources/motrpac_human-precovid_refmet-map_provenance"),
  versioned    = c(TRUE, TRUE, TRUE, TRUE, TRUE),
  required     = c(TRUE, TRUE, FALSE, FALSE, FALSE),
  affected_pkg = c("analysis", "analysis", "data", "data", "data"),
  stringsAsFactors = FALSE
)

# ---- Bucket files Stage 1 does not regenerate --------------------------------------
# These live in the bucket and must survive an upload. Nothing in the freeze produces
# them, so without this list every run would report them as orphans:
#
#   *_qc-report_*.html   per-ome QC reports, rendered by hand from the BIC QC notebooks
#                        (7 of them: 2 ATAC, 4 proteomics, 1 transcriptomics)
#   1kg_pca[_v2.0].csv   1000 Genomes PCA projection, produced outside this pipeline
#
# Stage 2 never deletes anything it did not just supersede, so this list changes nothing
# about what is removed — it decides whether an orphan is reported as expected (CARRIED)
# or as something to look at (ORPHANED).
CARRIED_FORWARD_RE <- c(
  "_qc-report_.*\\.html$",
  "^resources/motrpac_human-precovid_1kg_pca(_v[0-9]+\\.[0-9]+)?\\.csv$"
)

# Subdirs that carry an HTML QC report, so step 05 can check the ones that should have one
# instead of every subdir in the manifest. The two metabolomics subdirs are deliberately
# absent: no metabolomics QC report exists in the staging bucket, in production v1.3, or
# in the freeze, so including them would emit a warning on every run forever. Add a subdir
# here when a report for it starts shipping.
QC_REPORT_SUBDIRS <- c("epigenomics", "proteomics", "transcriptomics")

is_carried_forward <- function(rel_path) {
  Reduce(`|`, lapply(CARRIED_FORWARD_RE, function(re) grepl(re, rel_path)), FALSE)
}
